### ISSUE TITLE
playwright-cli has been superceded by playwright, and Mac arm64 does not work

### ISSUE THREAD

**Issue by thomergil** [naqvis/playwright-cr#2]
- playwright-cli is obsolete; Microsoft suggests to use npx playwright.
- shards install fails on a Mac with an arm64 chip.

**Comment by naqvis** [comment]
> * playwright-cli is obsolete; Microsoft suggests to use npx playwright.

That would be major change, as they might have updated their APIs as well. And I don't have enough bandwidth to manage this upgrade. Any PR is welcome



> * shards install fails on a Mac with an arm64 chip.

Its not Mac Arch issue, but the `playwright_cli` used by this shard, doesn't  provide chromium and/or other browsers drivers for latest osx: 

You can verify the same via invoke `bin/install_local_driver.sh` script as that's the script that got executed by `shards install` .

Running `playwright_cli install` on latest osx on M1 

```
Archive:  playwright-cli-0.180.0-next.1608746109749-cbc13bd-mac.zip
  inflating: ./playwright-cli
  inflating: ./browsers.json
  inflating: ./ffmpeg.COPYING.GPLv3
  inflating: ./ffmpeg-mac
Installing browsers for mac
Failed to install browsers
Error: Failed to download chromium, caused by
Error: ERROR: Playwright does not support chromium on mac14.3-arm64
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:143:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:168:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:101:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:60:5)
 ```
